CONFIG_CAN=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=y
CONFIG_LOG_BACKEND_SHOW_COLOR=y
CONFIG_MAIN_STACK_SIZE=8192


CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_CPP=y
CONFIG_CPP_EXCEPTIONS=y
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_CAN_STATS=y

# Keep your custom compiler flag:
CONFIG_COMPILER_OPT="-ftrack-macro-expansion=0"
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_PRINTK=y  

CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_SCHED_THREAD_USAGE=y
CONFIG_CPU_LOAD=y
CONFIG_STATS=y



# threading
CONFIG_MULTITHREADING=y 
CONFIG_NUM_COOP_PRIORITIES=127
CONFIG_NUM_PREEMPT_PRIORITIES=127
CONFIG_SCHED_SCALABLE=y