#pragma  once
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/drivers/can.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/types.h>
#include <stdio.h>
#include <sys/_intsup.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/sys/sys_heap.h>
#include <stddef.h>
#include <stdbool.h>
#include <zephyr/sys/mem_stats.h>
#include <zephyr/toolchain.h>
#include "syscalls/can.h"
#include <zephyr/debug/cpu_load.h>
#include <zephyr/sys/printk.h>
#include <zephyr/drivers/adc.h>
